version: '3'

services:
  web:
    build: .
    container_name: pg-transfers
    volumes:
      - /mnt/nfs:/app/uploads
    environment:
      - DOMAIN=transfer.pixelguardian.eu
    networks:
      - traefik-public
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.transfers.rule=Host(`transfer.pixelguardian.eu`)"
      - "traefik.http.services.transfers.loadbalancer.server.port=8000"

networks:
  traefik-public:
    external: true
